import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('about:blank');
  await page.goto('chrome-error://chromewebdata/');
  await page.goto('https://evisit.testotn.ca/');
  await page.goto('https://sso.testotn.ca/nidp//app/login?target=https%3A%2F%2Fsso.testotn.ca%2Fnidp%2Foauth%2Fnam%2Fauthz%3Fresponse_type%3Dcode%26client_id%3D95c20465-969a-4d97-ac72-231d31ce766c%26scope%3Dopenid%2Bprofile%2Botnhub_scopes%26state%3DSkSTJguwun7jFQhkwXqETaapt_nW8BuerckITULk-FY%3D%26redirect_uri%3Dhttps%3A%2F%2Fapi.awstestotn.ca%2Fopenidconnect%2Flogin%2Foauth2%2Fcode%2Fotn%26nonce%3DuIpnW_hNaWyAigp4KzCu5PWuVQ9WShPRh981fSoWaOI');
  await page.goto('https://sso.testotn.ca/nidp/app/login?id=OAUTH&sid=0&option=credential&sid=0&target=https%3A%2F%2Fsso.testotn.ca%2Fnidp%2Foauth%2Fnam%2Fauthz%3Fresponse_type%3Dcode%26client_id%3D95c20465-969a-4d97-ac72-231d31ce766c%26scope%3Dopenid%2Bprofile%2Botnhub_scopes%26state%3DSkSTJguwun7jFQhkwXqETaapt_nW8BuerckITULk-FY%3D%26redirect_uri%3Dhttps%3A%2F%2Fapi.awstestotn.ca%2Fopenidconnect%2Flogin%2Foauth2%2Fcode%2Fotn%26nonce%3DuIpnW_hNaWyAigp4KzCu5PWuVQ9WShPRh981fSoWaOI');
  await page.getByText('OTN Credentials').click();
  await page.getByPlaceholder('OTN Credentials').click();
  await page.getByPlaceholder('OTN Credentials').fill('bchawla@test.ca');
  await page.getByPlaceholder('OTN Credentials').press('Tab');
  await page.getByPlaceholder('Password').fill('test123!');
  await page.getByPlaceholder('Password').press('Enter');
  await page.getByRole('button', { name: 'Create event' }).click();
  await page.getByRole('button', { name: 'Schedule', exact: true }).click();
 
  await page.getByRole('button', { name: 'Schedule' }).click();

  await page.getByLabel('Start Time').click();
  await page.getByLabel('End Time').click();
  await page.getByLabel('Start Time').click();
  await page.locator('div').filter({ hasText: /^Start Time$/ }).click();
  await page.getByLabel('End Time').click();
  await page.locator('div').filter({ hasText: /^End Time$/ }).click();
  await page.getByText('Participating System(s)1 / 60 systemsOTN Member or SystemBeer Pratap Singh Chawl').click();
  await page.getByText('1 / 60 systems').click();
  await page.getByText('Participating System(s)1 / 60 systems').click();
  await page.getByText('OTN Member or System').click();
  await page.getByRole('option', { name: 'OTN Member or System' }).click();
  await page.getByText('OTN Member or System').click();
  await page.getByRole('option', { name: 'Guest via email (OTNinvite)' }).click();
  await page.getByText('Guest via email (OTNinvite)').click();
  await page.getByRole('option', { name: 'Non-OTN system (standards-based)' }).click();
  await page.getByText('Non-OTN system (standards-based)').click();
  await page.getByRole('option', { name: 'OTN Member or System' }).click();
  await page.getByPlaceholder('Search for people or room systems').click();
  await page.getByLabel('Close').click();
  await page.locator('div').filter({ hasText: /^Beer Pratap Singh ChawlaMy SystemOntario Telemedicine Network$/ }).nth(1).click();
  await page.getByRole('heading', { name: 'Event Preferences' }).click();
  await page.getByText('Opt out of PCVC time conflicts').click();
  await page.getByRole('checkbox').check();
  await page.getByRole('checkbox').uncheck();
  await page.getByRole('heading', { name: 'Scheduling Preferences' }).click();
  await page.getByText('Scheduling PreferencesEdit').click();
  await page.getByText('Administrative Contact:').click();
  await page.getByPlaceholder('Search for people or room systems').click();
  await page.getByPlaceholder('Search for people or room systems').fill('monica');
  await page.getByRole('option', { name: 'Monica Admin' }).click();
  await page.getByRole('button', { name: 'Schedule Event' }).click();
  await page.getByRole('alert').click();
  await page.getByLabel('Start Time').click();
  await page.getByLabel('Start Time').fill('11:48');
  await page.getByRole('button', { name: 'Schedule Event' }).click();
  await page.getByText('success - Event scheduled successfully').click();
  await page.getByRole('button', { name: 'Event Details' }).click();
  await page.locator('.MuiGrid-root > .MuiPaper-root').first().click();
  await page.getByText('Geriatric Medicine').click();
  await page.getByText('2025-01-16, 11:48 AM – 12:00 PM').click();
  await page.locator('div:nth-child(2) > .MuiPaper-root').first().click();
  await page.getByRole('heading', { name: 'Event ID' }).click();
  await page.getByText('6', { exact: true }).nth(1).click();
  await page.getByRole('heading', { name: 'Status' }).click();
  await page.getByText('Scheduled', { exact: true }).click();
  await page.getByRole('heading', { name: 'Consultant' }).click();
  await page.locator('div').filter({ hasText: /^ConsultantDr\. Beer Chawla$/ }).getByRole('paragraph').click();
  await page.getByRole('heading', { name: 'Administrative contact' }).click();
  await page.locator('div').filter({ hasText: /^Start Event$/ }).nth(1).click();
  await page.locator('div:nth-child(4) > div > .MuiPaper-root').click();
  await page.locator('div').filter({ hasText: /^Audio Connection Methods$/ }).nth(2).click();
  await page.getByText('Non-OTN system:').click();
  await page.getByRole('heading', { name: 'Participating Systems' }).click();
  await page.locator('div:nth-child(5) > div > div').click();
  await page.getByRole('heading', { name: 'Participating Systems' }).click();
  await page.getByText('2 systems').click();
  await page.locator('div').filter({ hasText: /^Dr\. Beer Pratap Singh ChawlaMy Systembchawla@test\.ca$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Mrs\. Monica Adminmadmin@tst\.ca$/ }).first().click();
  await page.locator('div:nth-child(6) > div > .MuiPaper-root').click();
  await page.getByRole('heading', { name: 'Patient Details' }).click();
  await page.locator('div').filter({ hasText: /^Number of patients:$/ }).click();
  await page.locator('div').filter({ hasText: /^Patient Letter:$/ }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('div').filter({ hasText: /^eVisit Patient Handout_20250116_1148am$/ }).click();
  const page1 = await page1Promise;
  await page.locator('div:nth-child(7) > div > .MuiPaper-root').click();
  await page.getByRole('heading', { name: 'Event Details' }).click();
  await page.getByText('Appointment Requirements:').click();
  await page.getByText('Cancel EventPrint').click();
  await page.getByRole('heading', { name: 'Cancel Event' }).click();
  await page.getByText('Are you sure you want to cancel this event?').click();
  await page.getByText('As the event has passed, when you click "Yes" a cancellation message will not be').click();
  await page.getByText('NoYes').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('alert').click();
  await page.locator('a').filter({ hasText: '303120624CANCELLED Clinical event (1 Patient)' }).click();
  await page.getByRole('heading', { name: 'Status' }).click();
  await page.locator('span').filter({ hasText: 'Cancelled' }).first().click();
});