import {test, expect, request} from "@playwright/test"
import {setReport, loadEnv } from "../../../helper/functions";
import {createHIALToken, ResponseValidation} from "../../../helper/APIfunctions";
import { Day } from '../../../helper/functions';
loadEnv('econsult_API_staging')
let apiContext; 
let regexMatchAll: RegExp = /(.*?)/;

test.beforeAll(async ({ playwright }) => {
    apiContext = await request.newContext({
        // All requests we send go to this API endpoint.
        baseURL: process.env.baseUrl,

    });
})
test.describe('21.Create a Case with long inputs in free-form fields -should fail', ()=> {

    test('21.Cannot create a Case with free-form fileds too long', async() => {
        setReport('econsult API', 'CreateCase')
        let date=new Day()
        const currentDate=date.caformatDate
        console.log(currentDate)
        const searchSpecialty=process.env.keywordSpec
        //consultantId is hardcoded; if the calcuation is needed execute SearchByNameAndSpeciality as a subtest before CreateCase
        const consultantId="practitioner/"+process.env.practitionerId
        const referrerUserl=createHIALToken(process.env.referrerUser)
        const diagnostics="User not found in eConsult"
        console.log(process.env.referrerUser)
        console.log("token " +referrerUserl)
       
       
        const res = await apiContext.post(`${process.env.baseURL}/referralRequest`, {
            data:{
              
                "resourceType": "ReferralRequest",
                "meta": {
                  "security": [
                    {
                      "extension": {
                        "url": "https://www.ehealthontario.ca/API/FHIR/StructureDefinition/eConsult/1/extension/limited_patient_consent_note",
                        "valueString": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad."
                      },
                      "system": "http://hl7.org/fhir/v3/ActCode",
                      "code": "CPLYCD",
                      "display": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad."
                    }
                  ]
                },
                "contained": [
                  {
                    "resourceType": "Patient",
                    "id": "1",
                    "contained": [
                      {
                        "resourceType": "Coverage",
                        "text": "OHIP",
                        "extension": [
                          {
                            "url": "www.ehealthontario.on.ca/FHIR2/StructureDefinition/extensions/OHIP_version_code",
                            "valueString": "22"
                          },
                          {
                            "url": "2.16.840.1.113883.4.59",
                            "valueString": "2222222222"
                          }
                        ]
                      }
                    ],
                    "name": {
                      "family": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad.",
                      "given": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad."
                    },
                    "gender": "M",
                    "birthDate": "2001-01-01"
                  },
                  {
                    "resourceType": "Composition",
                    "id": "1",
                    "text": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad."
                  }
                ],
                "extension": [
                  {
                    "url": "https://ehealthontario.on.ca/eConsult/FHIR2/StructureDefinition/extensions/tag",
                    "valueString": "EncounterID=45345435",
                    "_comment": "tag example"
                  },
                  {
                    "url": "https://ehealthontario.on.ca/eConsult/FHIR2/StructureDefinition/extensions/tag",
                    "valueString": "MRN=1234567",
                    "_comment": "another tag example"
                  },
                  {
                    "url": "https://ehealthontario.on.ca/eConsult/FHIR2/StructureDefinition/extensions/eConsult_title",
                    "valueString": "econsult title example one"
                  }
                ],
                "date": "Tue Jul 26 16:50:35 EDT 2016",
                "priority": {
                  "coding": {
                    "system": "2.16.840.1.113883.6.96",
                    "code": "394848005",
                    "display": "ROUTINE"
                  }
                },
                "patient": {
                  "reference": "contained/patient/1",
                  "_comment": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad."
                },
                "requester": {
                  "reference": "practitioner/@self",
                  "_comment": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad."
                },
                "recipient": {
                  "reference": consultantId,
                  "_comment": "this is the recipient"
                },
                "description": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad.",
                "serviceRequested": {
                  "coding": {
                    "system": "2.16.840.1.113883.6.96",
                    "code": "394848005",
                    "display": "Consultation"
                  }
                },
                "supportingInformation": [
                  {
                    "reference": {
                      "reference": "contained/composition/1",
                      "_comment": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad."
                    },
                    "display": "Magnis turpis scelerisque volutpat consectetuer placerat luctus arcu pharetra urna dapibus magnis risus dapibus dignissim. Massa lacinia. Volutpat id viverra magna ut cursus auctor nibh volutpat magna. Hac dapibus convallis. Porta maecenas maecenas convallis platea purus Enim at a venenatis augue ad tempus at elit torquent felis iaculis ultricies pharetra elementum malesuada. Habitant purus pretium lacinia sodales mi at pretium ridiculus nostra lacinia in at etiam massa. Consectetuer purus natoque orci vel eleifend egestas tincidunt suscipit. Montes feugiat velit id at fermentum nonummy vestibulum tempus nisi dictum velit sapien maecenas habitasse dolor. Ligula nascetur consectetuer aenean Ultrices, dictum. Nisi fringilla torquent felis vitae. Aenean dolor tempus praesent congue platea sed cursus facilisis Tellus viverra. Vel, consequat aenean accumsan odio non pulvinar. Nam per ad, habitasse mauris fames ac facilisis tortor. Volutpat potenti platea Tristique nam eros quam volutpat mollis dictum etiam venenatis, dapibus eleifend vel amet mattis molestie eu penatibus aliquet natoque ipsum tempor curae; dapibus id imperdiet mus accumsan metus scelerisque molestie. Proin molestie faucibus sagittis adipiscing vivamus quam luctus purus sollicitudin diam luctus sagittis leo dolor donec. Bibendum aptent. Cubilia blandit semper non mattis montes aenean nisl imperdiet proin Arcu, lectus class. Potenti eros nonummy euismod nunc cursus dapibus magna tortor imperdiet suspendisse Posuere enim. Et fusce augue. Hendrerit natoque Phasellus. Donec ac conubia sit purus felis nullam class varius pulvinar mus ut purus diam torquent tellus urna. Risus sem faucibus convallis purus odio sit adipiscing mi aliquet. Proin. Maecenas consequat vulputate vitae dui rhoncus donec taciti elementum vitae venenatis tempor malesuada nulla est cubilia. Lobortis commodo montes. Nisl, praesent fusce erat mus facilisi semper Platea turpis lorem diam orci netus, rhoncus. Ipsum tortor viverra. Condimentum ac quisque feugiat habitant, accumsan volutpat nibh Bibendum. Tortor, ut sollicitudin facilisis orci nascetur. Elementum purus fringilla torquent. Augue vel aliquam senectus imperdiet porta tortor dis. Aliquam arcu aliquam, sollicitudin pharetra lectus torquent. Non non platea rhoncus mus at platea phasellus urna turpis. Dolor augue hymenaeos. Neque proin, pretium urna quam cursus. Habitant vitae dis. Venenatis aenean, quis libero dictum, nisi condimentum netus Pharetra accumsan proin semper pede aliquet, amet morbi. Morbi, congue potenti nostra fringilla. Ullamcorper posuere hac. Nunc, accumsan tortor, vitae tempor. Dictum nulla potenti ipsum praesent congue at convallis tempus nibh proin torquent varius massa per urna lobortis magna proin hymenaeos nostra orci vitae quis lobortis. Orci platea tellus conubia. Mollis feugiat eleifend torquent torquent tincidunt. Morbi ad ad."
                  }
                ]
              },
            headers: { "Authorization": referrerUserl,
                       
                    },
                    
         })
        console.log(res)
        const body = await res.json()
        console.log(body)
        const reason=body.issue[0]['details']['coding']['code']
        const expected = {
          "resourceType": "OperationOutcome",
          "issue": [
            {
              "severity": "error",
              "details": {
                "coding": {
                  "system": "https://ehealthontario.ca/API/FHIR/NamingSystem/eConsult/1/eConsultErrors",
                  "code": "R_VALIDATION_ERROR",
                  "display": "Validation error"
                }
              },
              "diagnostics": "java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 24752 path $.supportingInformation[0].reference"
            }
          ]
        }
        

        console.log("-=Response Validation=-", ResponseValidation(expected,body))
        expect(res.status()).toEqual(400)
        expect(reason).toEqual('R_VALIDATION_ERROR')
        })  
 
        test.afterAll(async ({ }) => {
            // Dispose all responses.
            await apiContext.dispose();
        });
    })

    
